# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Terminal Banner Plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.12.0
      - run: chmod -R u+x .
      - run: cp ./index.mjs ./index.js
      - run: npm run build
      - name: 'Upload prepared files'
        uses: actions/upload-artifact@v4
        with:
          name: prepared-to-publish
          path: .

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20.12.0
          registry-url: https://registry.npmjs.org/
      - name: 'Download files to publish'
        uses: actions/download-artifact@v4
        with:
          name: prepared-to-publish
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
